name: Build JAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Verify Java installation
        run: java -version

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -Dorg.gradle.java.home=$JAVA_HOME

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: JAR
          path: build/libs/*.jar
